---
mariadb_packages:
  - 'mariadb'
  - 'python-pymysql'
mariadb_service_name: 'mariadb'
mariadb_user: 'mysql'
mariadb_group: 'mysql'
mariadb_config_path: '/etc/my.cnf'
mariadb_data_path: '/var/lib/mysql'
mariadb_pid_file: '/run/mysqld/mariadb.pid'
mariadb_socket_path: '/run/mysqld/mysqld.sock'
mariadb_base_dir: '/usr'
mariadb_setup_cmd: "mysql_install_db --user={{ mariadb_user | quote }} --datadir={{ mariadb_data_path | quote }} --auth-root-authentication-method=socket --skip-test-db"
